### ISSUE TITLE
An error was reported after the update

### ISSUE THREAD

**Issue by laitianwen** [GraftingRayman/ComfyUI_GraftingRayman#11]
Traceback (most recent call last):
  File "E:\sd\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2018, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "E:\sd\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_GraftingRayman\__init__.py", line 12, in <module>
    from .Nodes.GRPanOrZoom import GRPanOrZoom
  File "E:\sd\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_GraftingRayman\Nodes\GRPanOrZoom.py", line 6, in <module>
    from custom_controlnet_aux.depth_anything_v2.dpt import DepthAnythingV2
ModuleNotFoundError: No module named 'custom_controlnet_aux'

Cannot import E:\sd\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_GraftingRayman module for custom nodes: No module named 'custom_controlnet_aux'

**Comment by GraftingRayman** [comment]
I was initially using controlnet for depth, this has been removed

**Comment by laitianwen** [comment]
It seems to be working, thank you
