### ISSUE TITLE
ImportError: cannot import name 'GRPromptHub' from 'ComfyUI_GraftingRayman.Nodes.GRPrompt'

### ISSUE THREAD

**Issue by hjcxlp** [GraftingRayman/ComfyUI_GraftingRayman#5]
got this error, pls advise

Traceback (most recent call last):
  File "D:\ComfyUI-G\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-G\custom_nodes\ComfyUI_GraftingRayman\__init__.py", line 6, in <module>
    from .Nodes.GRPrompt import GRPromptSelector, GRPromptSelectorMulti, GRPromptHub
ImportError: cannot import name 'GRPromptHub' from 'ComfyUI_GraftingRayman.Nodes.GRPrompt' (D:\ComfyUI-G\custom_nodes\ComfyUI_GraftingRayman\Nodes\GRPrompt.py)

Cannot import D:\ComfyUI-G\custom_nodes\ComfyUI_GraftingRayman module for custom nodes: cannot import name 'GRPromptHub' from 'ComfyUI_GraftingRayman.Nodes.GRPrompt' (D:\ComfyUI-G\custom_nodes\ComfyUI_GraftingRayman\Nodes\GRPrompt.py)

**Comment by GraftingRayman** [comment]
Ooops, that was my mistake, forgot to add the node code for PromptHub

All sorted now
