### ISSUE TITLE
ComfyUI_GraftingRayman module for custom nodes: No module named 'rembg'

### ISSUE THREAD

**Issue by VitaliyAT** [GraftingRayman/ComfyUI_GraftingRayman#9]
Try install it and open workflow but getting such "Hi" from system.
I don;t know what to do in such situation: I manually clone repo to custom_nodes, I see that GR Prompt Selector is in work (not deleted from repo) but for some reasons ComfyUi 0.2.6 (the latest right now) cant load\find\work with this node.

Please help

```
************************************
* Loading GraftingRaymans GR Nodes *
************************************
Traceback (most recent call last):
  File "D:\Ai\SD\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2006, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\Ai\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_GraftingRayman\__init__.py", line 5, in <module>
    from .Nodes.GRImage import GRImageSize, GRImageResize, GRStackImage, GRResizeImageMethods, GRImageDetailsDisplayer, GRImageDetailsSave, GRImagePaste, GRImagePasteWithMask, GRBackgroundRemoverREMBG
  File "D:\Ai\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_GraftingRayman\Nodes\GRImage.py", line 25, in <module>
    from rembg import remove as rembg_remove
ModuleNotFoundError: No module named 'rembg'

Cannot import D:\Ai\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_GraftingRayman module for custom nodes: No module named 'rembg'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
```
I see that it cant find **rembg**, but it nothing say to me - Don't understand what I should do. I can just say "I can't find it too"

**Comment by GraftingRayman** [comment]
Hi

You need to install rembg,

you can run the following command:

pip install rembg

That will fix the issue
